name: cubepod

packages:
  - packages/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: dart analyze packages/
    description: Run Dart static analysis.
  test:
    exec: flutter test
    description: Run Flutter tests for a specific package.
    packageFilters:
      dirExists: test
