name: cubepod_testing
description: Mock containers, test observers, and utilities for testing CubePod applications.
version: 0.1.5
repository: https://github.com/iamglitch404/cubepod

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  cubepod_core: ^0.1.5
  cubepod_state: ^0.1.5

dev_dependencies:
  flutter_lints: ^3.0.0
