name: cubepod
description: A core component of the CubePod Application Runtime. Provides cubepod functionalities.
version: 0.1.4
repository: https://github.com/iamglitch404/cubepod

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  cubepod_core: ^0.1.0
  cubepod_state: ^0.1.0
  cubepod_flutter: ^0.1.0
  cubepod_async: ^0.1.0
  cubepod_query: ^0.1.0
  cubepod_network: ^0.1.0
  cubepod_events: ^0.1.0
  cubepod_sync: ^0.1.0
  cubepod_storage: ^0.1.0
  cubepod_router: ^0.1.0
  cubepod_enterprise: ^0.1.0
  cubepod_resources: ^0.1.0
  cubepod_scheduler: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
